#################
### Load data ###
#################

rm(list=setdiff(ls(),c('params','grp','treatment','injection.site','goi')))
print(grp)
print(treatment)
basedir <- params$basedir
setwd(basedir)
savedir <- paste(params$opdir,'diffmodel/bidirectional_onelm/',paste0(injection.site,collapse='-'),'/',sep='')
dir.create(savedir,recursive=T)

source('code/misc/fitfxns.R')
source('code/misc/miscfxns.R')
source('code/misc/plottingfxns.R')
load(paste0(params$opdir,'processed/pathdata.RData'))  # load path data and ROI names
load(paste0(savedir,grp,'_',treatment,'BidirectionalOptimOneLM_data.RData'))
if (treatment == '75 MLi-2'){tps = 6} else {tps=c(3,6)} # assign time points (3 and 6 mo for 0 and 450 MLi-2 treatment; 6 mo only for 75 MLi-2 treatment)
col <- getGroupColors(params$grps)[grp] # get color for plots

# exclude regions with 0 pathology at each time point for purposes of computing fit
for(t. in 1:length(df)){colnames(df[[t.]]) <- c('y','pred.retro','pred.antero')} # rename regression predictors for consistency and interpretability. This should actually be done in optimfxns.R: lm.mask.ant.ret.all
lapply(1:length(tps), function(t) paste0(t,' MPI: ',sum(df[[t]]$y != -Inf & !is.na(df[[t]]$pred.retro)),'/',nrow(df[[t]]),' regions left'))

##########################################################
### add together anterograde and retrograde prediction ###
##########################################################

# m is linear regression model objects that combine anterograde and retrograde predictions at each time point
# generated by code/diffmodel/optim_bidirectionalspread_onelm.R
df.rnames <- lapply(df,rownames)
vulnerability <- lapply(df.rnames, function(rn) residuals(m)[rn])
pred <- lapply(df.rnames, function(rn) m$fitted.values[rn])
path.t <- lapply(df.rnames, function(rn) m$model[rn,'y',drop=FALSE])

p <- lapply(1:length(tps), function(t) 
  p.xy(x=pred[[t]],y=path.t[[t]],ylab='Log(pathology)',xlab='Log(predicted)',
       ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste0(savedir,grp,'_',treatment,'Fit_bidirectionaladditivemodel.pdf'),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# plot fit and label each region
geom_label_repel(aes(label = Region),
                 point.padding = 0.5,
                 segment.color = 'grey50')
p <- list()
for(t. in 1:length(tps)){
  t.path.names <- substr(names(pred[[t.]]),1,nchar(names(pred[[t.]]))-2)
  df.tmp <- data.frame(x=pred[[t.]],y=path.t[[t.]],lab=t.path.names)
  df.tmp$z <- scale(df.tmp$x,center=T)
  df.tmp <- df.tmp[abs(df.tmp$z) >1.5,]
  p[[t.]] <- p.xy(x=pred[[t.]],y=path.t[[t.]],ylab='Log(pathology)',xlab='Log(predicted)',
   ttl=paste0(grp,': ',tps[t.],' MPI'),col=col,alpha=0.7) + geom_label_repel(data=df.tmp,aes(x=x,y=y,label=lab),
                     point.padding = 0.5,label.size=0.05,size=1,label.r=0.1,
                     segment.color = 'grey50')
}
  
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste0(savedir,grp,'_',treatment,'Fit_bidirectionaladditivemodel_label_repel.pdf'),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# plot fit and separately display hemispheres

p <- lapply(1:length(tps), function(t) 
  p.xyc(x=pred[[t]],y=path.t[[t]],ca=substr(rownames(path.t[[t]]),1,1),ylab='Log(pathology)',xlab='Log(predicted)',
        ttl=paste0(grp,': ',tps[t],' MPI'),col=col,alpha=0.7) + 
    theme(legend.position = c(0.1,1),legend.background=element_blank(),legend.key.size = unit(0.1, "cm"),legend.title = element_blank()))
p <- plot_grid(plotlist=p,align='hv',nrow=1)
ggsave(p,filename = paste0(savedir,grp,'_',treatment,'FitHemiColor_bidirectionaladditivemodel.pdf'),
       units = 'cm',height = 3.75,width = 3.75*length(tps),useDingbats=FALSE)

# initialize empty data frame with all regions and time points
df.vuln <- df.pred <- data.frame(matrix(ncol=length(tps),nrow=length(path.names), dimnames=list(path.names, paste(tps,'MPI'))),check.names = FALSE)
for(t in 1:length(tps)){
  regions.mpi <- names(vulnerability[[t]]) # get the regions that had non-zero pathology at each tp (so log can be computed)
  regions.mpi.path.names <- substr(regions.mpi,1,nchar(regions.mpi)-2) # get names of regions without "_1" ("_$MPI") appended
  df.vuln[regions.mpi.path.names,paste(tps[t],'MPI')] <- vulnerability[[t]][regions.mpi]
  df.pred[regions.mpi.path.names,paste(tps[t],'MPI')] <- pred[[t]][regions.mpi]
}

# compute intrinsic vulnerability as an average over time and hemispheres
hemi.average.vuln <- hemi.average(df.vuln)
write.csv(hemi.average.vuln,paste0(savedir,grp,'_',treatment,'vulnerability_bidirectional_hemiaverage.csv'))

write.csv(df.vuln,paste0(savedir,grp,'_',treatment,'vulnerability_bidirectional.csv')) # save vulnerability for each time point

write.csv(df.pred,paste0(savedir,grp,'_',treatment,'log10predictedpath_bidirectional.csv')) # save log10 predicted path
